from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class SimulationMode(StrEnum):
    BACKTEST = "BACKTEST"
    REPLAY = "REPLAY"
    PAPER = "PAPER"
    LIVE = "LIVE"


class VerificationLevel(StrEnum):
    VERIFIED = "VERIFIED"
    RESEARCH = "RESEARCH"
    SYNTHETIC = "SYNTHETIC"


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class TimeInForce(StrEnum):
    DAY = "DAY"
    GTC = "GTC"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"


class EventType(StrEnum):
    SESSION_START = "SESSION_START"
    SETTLEMENT = "SETTLEMENT"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    BAR_OPEN = "BAR_OPEN"
    OPEN_ORDER_MATCH = "OPEN_ORDER_MATCH"
    STRATEGY_OPEN_CALLBACK = "STRATEGY_OPEN_CALLBACK"
    STRATEGY_CALLBACK = "STRATEGY_CALLBACK"
    INTRADAY_ORDER_PROCESSING = "INTRADAY_ORDER_PROCESSING"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_TRIGGERED = "ORDER_TRIGGERED"
    ORDER_PARTIAL_FILL = "ORDER_PARTIAL_FILL"
    ORDER_FILL = "ORDER_FILL"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_EXPIRED = "ORDER_EXPIRED"
    BAR_CLOSE = "BAR_CLOSE"
    STRATEGY_CLOSE_CALLBACK = "STRATEGY_CLOSE_CALLBACK"
    POST_CLOSE_ORDER_VALIDATION = "POST_CLOSE_ORDER_VALIDATION"
    MARK = "MARK"
    VALUATION = "VALUATION"
    LEDGER_ENTRY = "LEDGER_ENTRY"
    PORTFOLIO_SNAPSHOT = "PORTFOLIO_SNAPSHOT"
    SESSION_END = "SESSION_END"


class LedgerEntryType(StrEnum):
    CASH_DEPOSIT = "CASH_DEPOSIT"
    CASH_WITHDRAWAL = "CASH_WITHDRAWAL"
    TRADE_PRINCIPAL = "TRADE_PRINCIPAL"
    COMMISSION = "COMMISSION"
    FEE = "FEE"
    DIVIDEND = "DIVIDEND"
    INTEREST = "INTEREST"
    BORROW_FEE = "BORROW_FEE"
    SETTLEMENT = "SETTLEMENT"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    CASH_IN_LIEU = "CASH_IN_LIEU"


class CorporateActionType(StrEnum):
    SPLIT = "SPLIT"
    CASH_DIVIDEND = "CASH_DIVIDEND"


class SimulationRunStatus(StrEnum):
    QUEUED = "QUEUED"
    VALIDATING_DATA = "VALIDATING_DATA"
    BUILDING_MANIFEST = "BUILDING_MANIFEST"
    RUNNING = "RUNNING"
    FINALIZING = "FINALIZING"
    DONE = "DONE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SimulationErrorCode(StrEnum):
    DATA_VERSION_REQUIRED = "DATA_VERSION_REQUIRED"
    DATA_VERSION_NOT_FOUND = "DATA_VERSION_NOT_FOUND"
    INSTRUMENT_NOT_FOUND = "INSTRUMENT_NOT_FOUND"
    INSTRUMENT_DATA_NOT_FOUND = "INSTRUMENT_DATA_NOT_FOUND"
    VERIFIED_DATA_MISSING = "VERIFIED_DATA_MISSING"
    INVALID_OHLC = "INVALID_OHLC"
    DUPLICATE_BAR = "DUPLICATE_BAR"
    INVALID_CORPORATE_ACTION = "INVALID_CORPORATE_ACTION"
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    INVALID_ORDER = "INVALID_ORDER"
    ORDER_REJECTED = "ORDER_REJECTED"
    UNSUPPORTED_ORDER_TYPE = "UNSUPPORTED_ORDER_TYPE"
    UNSUPPORTED_ASSET_CLASS = "UNSUPPORTED_ASSET_CLASS"
    ENGINE_INVARIANT_FAILED = "ENGINE_INVARIANT_FAILED"
    LEDGER_RECONCILIATION_FAILED = "LEDGER_RECONCILIATION_FAILED"
